### ISSUE TITLE
Please provide clean source tarballs

### ISSUE THREAD

**Issue by dpocock** [xtuple/qt-client#175]
The 4.1.0 source tarball appears to simply be a snapshot of the developer workspace where the 4.1.0 binary for Mac OS X was built.  It includes copy of things like .gitignore and .gitmodules and entire copies of the submodules.  It also includes copies of binaries compiled for Mac OS X.  It includes various transient/generated files that cause the build to fail on other platforms and users on other platforms have to explicitly delete those files and "make clean" before using the tarball.

For the 4.2.0 release, could you please use a mechanism such as "make dist" to generate a pure source tarball?  I am happy to assist in testing such a tarball.

I'm not sure if qmake fully supports "dist" targets though:

https://bugreports.qt-project.org/browse/QTBUG-21910

and it may be necessary to make some helper script for making the source tarball.

**Comment by gilmoskowitz** [comment]
Addressed as described above - github-generated tarballs and pull requests against openrpt and csvimp.
