### ISSUE TITLE
SQL bug in trigger on accnt

### ISSUE THREAD

**Issue by dpocock** [xtuple/qt-client#346]
I was just looking at the trigger _accnttrigger() and noticed this:

```
  SELECT (metric_value='t')
    INTO ffProfit
    FROM metric
   WHERE(metric_name='GLFFProfitCenters')
   LIMIT 1;
  ffProfit := COALESCE(ffSub, false);
```

I believe the last line should not refer to ffSub

This is in the 4.1.0 quickstart schema in the package - I don't know if it has been fixed in a later schema.

**Comment by gilmoskowitz** [comment]
fixed by xtuple/xtuple#1490
