### ISSUE TITLE
Plugin for PostBooks client

### ISSUE THREAD

**Issue by mbnoimi** [xtuple/qt-client#347]
Hi,

Recently I got my own workshop so I want to use PostBooks for manging my finances but I need to create a customized Purchase/Sale/Manufacture forms in addition to login form (need for calculations for aluminum cuts & quick multi-language switching).

I don't want to fork PostBooks and lost the recent modifications of community edition

I wonder how can I do that? Is there any reference point to it? Is there any repository to share my plugins in case this feature is already exists (other than Github)?

P.S.
* I've fine knowledge in Qt but I just want to know the right place to start from.
* I forced to post this inquiry here because I can't access your website as shows here(https://github.com/xtuple/qt-client/issues/249)

**Comment by gilmoskowitz** [comment]
Info on fixing and extending the desktop client is available on the [qt-client wiki](https://github.com/xtuple/qt-client/wiki/Hacking-the-xTuple-Desktop-Client---An-Overview).
