### ISSUE TITLE
Missing relations in Quickstart DB

### ISSUE THREAD

**Issue by devdesco-ceo** [xtuple/qt-client#559]
Wed Dec 10 10:25:04 2014 ERROR:  relation "api.customer" does not exist
LINE 1: SELECT cust_id, api.customer.* FROM api.customer  JOIN custi...
                                            ^
QPSQL: Unable to create query
SELECT cust_id, api.customer.* FROM api.customer  JOIN custinfo ON cust_number = customer_number  where active = true
Wed Dec 10 10:25:04 2014 ERROR:  relation "api.vendor" does not exist
LINE 1: SELECT vend_id, api.vendor.* FROM api.vendor  JOIN vendinfo ...
                                          ^
QPSQL: Unable to create query
SELECT vend_id, api.vendor.* FROM api.vendor  JOIN vendinfo ON vend_number = vendor_number  where active = true AND vendor_type <> 'TAX AUTHORITY'
Wed Dec 10 10:25:09 2014 ERROR:  relation "api.customer" does not exist
LINE 1: SELECT cust_id, api.customer.* FROM api.customer  JOIN custi...
                                            ^
QPSQL: Unable to create query
SELECT cust_id, api.customer.* FROM api.customer  JOIN custinfo ON cust_number = customer_number  where active = true
Wed Dec 10 10:25:09 2014 ERROR:  relation "api.vendor" does not exist
LINE 1: SELECT vend_id, api.vendor.* FROM api.vendor  JOIN vendinfo ...
                                          ^
QPSQL: Unable to create query
SELECT vend_id, api.vendor.* FROM api.vendor  JOIN vendinfo ON vend_number = vendor_number  where active = true AND vendor_type <> 'TAX AUTHORITY'
Wed Dec 10 10:25:14 2014 ERROR:  relation "api.customer" does not exist
LINE 1: SELECT cust_id, api.customer.* FROM api.customer  JOIN custi...
                                            ^
QPSQL: Unable to create query
SELECT cust_id, api.customer.* FROM api.customer  JOIN custinfo ON cust_number = customer_number  where active = true
Wed Dec 10 10:25:14 2014 ERROR:  relation "api.vendor" does not exist
LINE 1: SELECT vend_id, api.vendor.* FROM api.vendor  JOIN vendinfo ...
                                          ^
QPSQL: Unable to create query
SELECT vend_id, api.vendor.* FROM api.vendor  JOIN vendinfo ON vend_number = vendor_number  where active = true AND vendor_type <> 'TAX AUTHORITY'

**Comment by gilmoskowitz** [comment]
This issue appears to be fixed in 4.8.0.
