### ISSUE TITLE
Struggling with QNetworkRequest 

### ISSUE THREAD

**Issue by szuke** [xtuple/qt-client#626]
I've been fighting through using QNetworkRequest for doing a POST with a SOAP request. I am able to successfully do a POST, the ccvoid.js example was helpful. What I'm fighting with is the ability to set headers. I'm hoping this is something I'm doing wrong. The following example is a simple one. I am able to successfully set the URL, but when setting the header using __setHeader()__ I end up with a TypeError. This appears to be telling me that I cannot use the setHeader(QNetworkRequest::KnownHeaders,QVariant) function. This is set to INVOKABLE in the QNetworkRequestProto header file.

```javascript
var netrequest = new QNetworkRequest();
netrequest.setUrl(QUrl("http://core-1.doubleu.mobi/Mecaniquews/service/mecanique.asmx?op=GetFullDetails"));

netrequest.setHeader("ContentTypeHeader", "text/xml;charset=utf-8");
```

*TypeError: cannot call setHeader(): argument 1 has unknown type `QNetworkRequest::KnownHeaders' (register the type with qScriptRegisterMetaType())*

**Comment by davidbeauchamp** [comment]
It is exposed however the "QNetworkRequest" types are not. 

No worries, though, you can use .setRawHeader. I've used the following line of code:

``
netrequest.setRawHeader(new QByteArray("Content-Type"), new QByteArray("text/xml;charset=utf-8"));
``

**Comment by davidbeauchamp** [comment]
Something you might also find help is a way to set the post body, I've included it below with your code modified slighty:

```
var netmanager = new QNetworkAccessManager(mywindow);
var netrequest = new QNetworkRequest();

// put this into its own var because we want to do manipulate
var url = new QUrl("http://core-1.doubleu.mobi/Mecaniquews/service/mecanique.asmx?op=GetFullDetails");

// add parameters to the url string
url.addQueryItem("SampleParameter", "SampleValue");

netrequest.setUrl(url);

// give the netmanager the encoded query as the post body
netmanager.post(netrequest, url.encodedQuery());
```

**Comment by szuke** [comment]
Thanks for the feedback. This was just a stub I was using for testing, the "real" code is prettier. 

That worked like a charm. Any tricks for using setAttribute? 

Thanks again.
Scott

**Comment by davidbeauchamp** [comment]
Are you getting a type error with that? Unfortunately it doesn't look like there is a setRawAttribute so if setAttribute is erroring I am not sure what we could do (other than exposing the types to script, but that would require a new binary). 

You might be able to get away with putting the integer value in place of the constant though, http://qt-project.org/doc/qt-4.8/qnetworkrequest.html#Attribute-enum

**Comment by szuke** [comment]
I originally tried using an integer, but no dice. Is there anyway to define the type at runtime? 

I should be ok without it right now, but I know it's going to hit me eventually. This would be great to get into the binary at some point. I am happy to help with this one.

**Comment by davidbeauchamp** [comment]
Please file an incident in dogfood to expose the QNetworkRequest types to the scripting engine. It isn't a difficult process but I intend to ask @gilmoskowitz for assistance. You can see a sample of what is necessary [here](https://github.com/xtuple/qt-client/blob/b9c48e21c0dacbc4a61afc79b0aae64d127915dc/scriptapi/qprocessproto.cpp#L52).

**Comment by szuke** [comment]
I'll fine an incident. I had started to look at the qScriptRegisterMetaType function, but hadn't dug very far. 

Thanks for your help with this issue.
