### ISSUE TITLE
checkbox in XTreeWidget???

### ISSUE THREAD

**Issue by szuke** [xtuple/qt-client#634]
Has anyone managed to add a checkbox to an XTreeWidget?

I am attempting to implement the following code, but "setFlags" and "setCheckState" aren't exposed. 

Is there another way to pull this off?

var row = new XTreeWidgetItem(_orders, counter, orders[prop].BuyerInformation.Name.toString(), orders[prop].PONumber.toString(), orders[prop].CustomerProductId.valueOf(), orders[prop].Description.toString(), orders[prop].QtyReq.valueOf(), orders[prop].DeliverBy.valueOf(), orders[prop].LineStatus.toString() );
row.setFlags(Qt.ItemIsUserCheckable);
row.setCheckState(0,Qt.Checked);

**Comment by gilmoskowitz** [comment]
replaced by https://www.xtuple.org/xtincident/view/bugs/26790
