### ISSUE TITLE
Qt5

### ISSUE THREAD

**Issue by discountscott** [xtuple/qt-client#671]
Is xTuple able to be compiled using QT5 yet? What's the timeline for that? I know it was in the works - but I still get errors regarding obsolete/deprecated functions/members (namely toAscii,WFlags,setAcceptsHoverEvents,QUrl::queryItemValue,QHeaderView::setClickable).

**Comment by gilmoskowitz** [comment]
@discountscott - The Qt5 work is a work in progress. The code is on a branch in one of our developer's forks and is being tested. We have not merged it to a release branch yet. Our _goal_ is to merge it in for a 4.9.0Beta2.

**Comment by discountscott** [comment]
@gilmoskowitz - Very nice! I appreciate the update.

**Comment by davidbeauchamp** [comment]
We are publishing Qt5 nightlies if you wanted to get your hands on it sooner (we would definitely appreciate more eyes on them!)  -- http://sourceforge.net/projects/postbooks/files/11%20PostBooks-nightly/2015-04-27/

**Comment by discountscott** [comment]
@davidbeauchamp I'll definitely put my hands on it!
