### ISSUE TITLE
guiclient does not compile

### ISSUE THREAD

**Issue by extremelydangerous** [xtuple/qt-client#751]
![captura_de_tela-2](https://cloud.githubusercontent.com/assets/8309298/8305886/72f67286-1989-11e5-8261-56694d730394.png)

when compile  from sources using clang++  on FreeBSD10 AMD64, using qt-4.8.6
All other modules, compiles OK

**Comment by extremelydangerous** [comment]
this is the result of only Q_OS_LINUX , Q_OS_MAC and Q_OS_LINUX, but QT on FreeBSD defines Q_OS_FREEBSD,
I am going to make   a patch for it to compile

**Comment by gilmoskowitz** [comment]
replaced by https://www.xtuple.org/xtincident/view/bugs/26791
