### ISSUE TITLE
Error building qt-client on Mac

### ISSUE THREAD

**Issue by cwrinn** [xtuple/qt-client#787]
```
cd guiclient/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
make[1]: *** No rule to make target `../../openrpt/lib/libMetaSQL.dylib', needed by `../bin/xtuple.app/Contents/MacOS/xtuple'.  Stop.
```

openrpt appears to build using static libs but qt-client is requiring dylib. There's a successfully built libMetaSQL.a file in '../../openrpt/lib/'.

I am mostly following your steps at https://github.com/xtuple/qt-client/wiki/Desktop-Development-Environment-Setup. The main difference is that openrpt, csvimp and qt-client are located in the same folder, but that has never been an issue in the past.

I need to deliver an xTuple 4.7.0 client with a slightly customized 'openrpt' to a client for approval that a feature request works the way they want it to before we create a pull request back to you guys to contribute back the feature.

~ ~ ~ ~
Christopher Wrinn
Paladin Logic, Limited - IT Director/Project Manager.

**Comment by gpazo** [comment]
The qt-client build will look for an openrpt build directory in either the current working directory or the parent directory directly above qt-client once you have successfully built openrpt; the reference for this is in the global.pri file here: https://github.com/xtuple/qt-client/blob/4_10_x/global.pri#L18

**Comment by cwrinn** [comment]
Thanks, but I'm aware of that; having built xTuple for years here at Paladin Logic. What I don't get is why suddenly I am getting this error about no rule to make target "libMetaSQL.dylib".

**Comment by gpazo** [comment]
I think you need to update your openrpt, as we did make a change from static to shared, here: https://github.com/xtuple/openrpt/pull/30

if you:```cd openrpt && make distclean```
then: ```git remote add XTUPLE https://github.com/xtuple/openrpt.git```
```git fetch XTUPLE```
```git checkout XTUPLE/tags/v3.3.10```
```qmake && make```
then re-try building your qt-client. Hope this helps!

**Comment by cwrinn** [comment]
Still have the same error. OpenRPT still appears to be built using static libs.

**Comment by gilmoskowitz** [comment]
@cwrinn - The current OpenRPT on Macs should build with static libraries. We tried to switch to dynamic libraries on all three primary platforms while we were working on xTuple ERP release 4.7.0. That experiment failed and we switched back to static libraries for Windows and Mac OS X. It looks like the code you're working with in qt-client doesn't match the code in openrpt.

Try `make distclean` in `qt-client`, then edit `qt-client/global.pri` like so:
```
@@ -96,12 +97,14 @@ isEmpty( OPENRPT_IMAGE_DIR ) {
 
 OPENRPTLIBEXT = $${QMAKE_EXTENSION_SHLIB}
 XTLIBEXT      = $${QMAKE_EXTENSION_SHLIB}
+win32:OPENRPTLIBEXT = a
+win32:XTLIBEXT      = a
+macx:OPENRPTLIBEXT  = a
+macx:XTLIBEXT       = a
 isEmpty( OPENRPTLIBEXT ) {
-  win32:OPENRPTLIBEXT = a
   unix:OPENRPTLIBEXT  = so
 }
 isEmpty( XTLIBEXT ) {
-  win32:XTLIBEXT = a
   unix:XTLIBEXT  = so
 }
```

This should tell qmake to create Makefiles that link with static OpenRPT libraries and also to build static libraries for the qt-client code.

**Comment by cwrinn** [comment]
Gil,

Thanks. It is building know, I will let you know of the progress.

FYI, I am currently checked out on tag v4.7.0 as that is what the customer
in question is running. However, I tried on tag v4.9.0 as well with the
same issue.

**Comment by cwrinn** [comment]
It completes the build now, after I made this change to qt-client/common/common.pro:
```diff
diff --git a/common/common.pro b/common/common.pro
index b8111b5..2b18eb5 100644
--- a/common/common.pro
+++ b/common/common.pro
@@ -2,13 +2,15 @@ include( ../global.pri )
 
 TARGET      = xtuplecommon
 TEMPLATE    = lib
-CONFIG      += qt warn_on dll
+CONFIG      += qt warn_on
 # TEMPORARY HACK
-win32 {
-  CONFIG -= dll
+win32 | macx {
   CONFIG += staticlib
+} else {
+  CONFIG += dll
 }
 
+
 DEFINES     += MAKELIB
 
 INCLUDEPATH += $(QTDIR)/src/3rdparty/zlib
```

And now I get:
```error
Dyld Error Message:
  Library not loaded: libxtuplecommon.1.dylib
  Referenced from: /Users/USER/*/xtuple.app/Contents/MacOS/xtuple
  Reason: image not found
```

**Comment by cwrinn** [comment]
Wrong button...

**Comment by gilmoskowitz** [comment]
@cwrinn - So this is an old problem with dynamic libraries and is part of why we reverted to static linking. You have to set the runtime environment so the application knows where to look for dynamic libraries. For testing purposes you can use the DYLD_LIBRARY_PATH environment variable and launch from the command line. See the man page for `dyld`. When you go to bundle the application, send me an email and we can discuss what's involved (too much to go into here).

**Comment by cwrinn** [comment]
I think something else is wrong in this case, Gil.

xtuplecommon building as a dylib when I explicitly told it to be static. I'm going to try to make the section of common.pro above match the one in 4.9.0 in case I have a hard to spot syntactical error. That's building now.

**Comment by cwrinn** [comment]
That appeared to do it. I'm having our QA test it today. Will re-open if necessary. Thanks for the help, Gil!
